#!/usr/bin/env bash

# Open $1 in emacsclient, but using using artemis-mode rather than text-mode.
# Opening files and evaluating Lisp are mutually exclusive, so we must run two
# commands.
emacsclient "$1" &
sleep 1
emacsclient --eval "(switch-to-artemis \"$1\")"

wait
