#!/usr/bin/env bash

# Close the given Artemis issue ID

[[ "$#" -eq 1 ]] || {
    echo "artemis-close requires (prefix of) an issue ID. Open issues:" 1>&2
    artemis list 1>&2
    exit 1
}

artemis add "$1" -p state=resolved -p resolution=fixed
