#!/usr/bin/env bash
set -e

DIR="/tmp/test_results.individual"

  COUNT=0
SUCCESS=0
   FAIL=0

if [[ -e "$DIR" ]]
then
      COUNT=$(ls -1 "$DIR"        | wc -l)
    SUCCESS=$(grep -R PASS "$DIR" | wc -l)
       FAIL=$(grep -R FAIL "$DIR" | wc -l)
fi

if [[ "$FAIL" -eq 0 ]]
then
    echo "<fc=#00FF00>$SUCCESS/$COUNT</fc>"
else
    echo "<fc=#FF0000>$SUCCESS/$COUNT</fc>"
fi
