#!/usr/bin/env python
"""Print the names of failing store test cases"""

import os
import sys
from lxml import etree

# TODO: Read this from a config file
result_dir = '/home/chris/test-results'

# Loop through all XML result files and grab those which have failures
failures = {}
for f in [g for g in os.listdir(result_dir) if g.endswith('.xml')]:
    count = len(etree.parse(result_dir + '/' + f).xpath('//failure'))
    if count > 0:
        failures[f[:-4]] = count # Chop off the '.xml'

if len(failures) == 0 and '-xmobar' in sys.argv:
    print '<fc=#44FF44>Tests pass</fc>'
    sys.exit()

# Output the results, based on our arguments
count  = {True:  lambda s: ' ' + str(failures[s]),
          False: lambda s: ''                    }['-n' in sys.argv]
sep    = {True:  ' | ',
          False: '\n' }['-p' in sys.argv]
format = {True:  lambda n: '<fc=#FF4444>' + n + '</fc>',
          False: lambda n: n                           }['-xmobar' in sys.argv]

print sep.join(map(lambda s: s + format(count(s)), failures))
