#!/bin/bash

# Wrapper around storetest-real which ensures it runs as the right user

# See who owns the store
STOREOWNER=$(stat -c %U /var/www/domains/wandisco.com/drupal7/htdocs)

# Are we root?
if [ $(whoami) = "root" ]; then
  # Yes; make a new RAM database for the tests
  # TODO
  # Run the tests as the correct user
  sudo -u $STOREOWNER /usr/local/bin/storetest-real $@
else
  # No. Use (gk)sudo to become root then recurse
  command -v gksudo >/dev/null 2>&1 && { gksudo true; }
  sudo -u root /usr/local/bin/storetest $@
fi
