#!/bin/bash

# Wrapper around storetest-real which ensures it runs as the right user

# See who owns the store
STOREOWNER=$(stat -c %U /var/www/domains/wandisco.com/drupal7/htdocs)

# Is it us?
if [ $(whoami) = $STOREOWNER ]; then
  # Yes, run the tests
  /usr/local/bin/storetest-real $@
else
  # No, recurse as the correct user, using gksudo if available
  command -v gksudo >/dev/null 2>&1 && { gksudo true; }
  sudo -u $STOREOWNER /usr/local/bin/storetest $@
fi
