#!/usr/bin/env bash
shopt -s nullglob

    ALL=$(find ~/System/Tests/scripts/         -type f | wc -l)
   PASS=$(find ~/System/Tests/results/pass/    -type f | wc -l)
  CHECK=$(find ~/System/Tests/results/check/   -type f | wc -l)
RUNNING=$(find ~/System/Tests/results/running/ -type f | wc -l)

SUCCESS=$(( PASS + CHECK ))

DIFF=$(( ALL - SUCCESS ))

EXTRA=""
[[ "$RUNNING" -ne 0 ]] || EXTRA=" so far"

HEX="#00FF00"
[[ "$DIFF" -gt 0 ]] && HEX="#FF0000"

echo "<fc=${HEX}>${SUCCESS}/${ALL} passed${EXTRA}</fc>"

[[ "x$1" = "xshow" ]] || exit 0

echo "PASS:    $PASS"
echo "CHECK:   $CHECK"
echo "SUCCESS: $SUCCESS"
echo "RUNNING: $RUNNING"
echo "ALL:     $ALL"

echo "Passed:"
ls ~/System/Tests/results/pass/
echo ""

echo "To check:"
ls ~/System/Tests/results/check/

echo "Not run:"
for TEST in ~/.tests/scripts/*
do
    NAME=$(basename "$TEST")
    [[ -e ~/System/Tests/results/stdout/"$NAME" ]] || echo "$NAME"
done
echo ""

echo "Failures:"
for TEST in ~/System/Tests/scripts/*
do
    NAME=$(basename "$TEST")
    [[ -e ~/.tests/results/stdout/"$NAME" ]] || continue
    [[ -e ~/.tests/results/pass/"$NAME"   ]] && continue
    [[ -e ~/.tests/results/check/"$NAME"  ]] && continue
    echo "$NAME"
done
