#!/usr/bin/env bash
shopt -s nullglob

D="$HOME/System/Tests"

function count {
    find "$D/$1" -type f -o -type l | wc -l
}

    ALL=$(count scripts/)
   PASS=$(count results/pass/)
  CHECK=$(count results/check/)
RUNNING=$(count results/running/)

SUCCESS=$(( PASS + CHECK ))

DIFF=$(( ALL - SUCCESS ))

HEX="#00FF00"
[[ "$DIFF" -gt 0 ]] && HEX="#FF0000"

echo "<fc=${HEX}>${SUCCESS}/${ALL}</fc>"

[[ "x$1" = "xshow" ]] || exit 0

echo "PASS:    $PASS"
echo "CHECK:   $CHECK"
echo "SUCCESS: $SUCCESS"
echo "RUNNING: $RUNNING"
echo "ALL:     $ALL"

echo "Passed:"
ls "$D/results/pass/"
echo ""

echo "To check:"
ls "$D/results/check/"

echo "Not run:"
for TEST in "$D/scripts"/*
do
    NAME=$(basename "$TEST")
    [[ -e "$D/results/stdout/$NAME" ]] || echo "$NAME"
done
echo ""

echo "Failures:"
for TEST in "$D/scripts"/*
do
    NAME=$(basename "$TEST")
    [[ -e "$D/results/stdout/$NAME" ]] || continue
    [[ -e "$D/results/pass/$NAME"   ]] && continue
    [[ -e "$D/results/check/$NAME"  ]] && continue
    echo "$NAME"
done
