#!/usr/bin/env bash

function choose {
    # Choose one test at random
    find results/pass -type f | shuf | head -n1

    # Choose the oldest test
    # shellcheck disable=SC2012
    ls -1tr results/pass | head -n1
}

# Keep running the test suite until killed

cd ~/System/Tests || exit 1
while true
do
    # Only run tests if we're on AC power
    if ! plugged_in
    then
        echo "Skipping as not plugged in" 1>&2
    elif hot
    then
         echo "Skipping as we're running hot" 1>&2
    else
        # Force some tests to be re-run
        while read -r TST
        do
            touch results/pass/"$TST"
            mv results/pass/"$TST" results/check/
        done < <(choose)

        nix-shell --run "./run"
        echo "Done" 1>&2
    fi

    # Wait long enough to be killed, beaten to the testing lock, etc.
    echo "Sleeping" 1>&2
    sleep 60
    echo "Woke up" 1>&2
done
