#!/usr/bin/env bash

function choose {
    # Choose one test at random
    SHUF=$(ls     results/pass | shuf)

    # Choose the oldest test
    TIME=$(ls -tr results/pass)

    echo "$SHUF" | head -n1
    echo "$TIME" | head -n1
}

# Keep running the test suite until killed

cd ~/System/Tests
while true
do
    # Only run tests if we're on AC power
    if plugged_in
    then
        # Force some tests to be re-run
        while read -r TST
        do
            touch results/pass/"$TST"
            mv results/pass/"$TST" results/check/
        done < <(choose)

        nix-shell --run "./run"
        echo "Done" 1>&2
    fi

    # Wait long enough to be killed, beaten to the testing lock, etc.
    echo "Sleeping" 1>&2
    sleep 60
    echo "Woke up" 1>&2
done
