#!/bin/sh

# Put a symlink to the argument in ~/System/Programs/bin
echo "Making $1 executable"
chmod +x $1

CWD=$(pwd)
echo "Linking $CWD/$1 to ~/System/Programs/bin/$1"
ln -s $CWD/$1 ~/System/Programs/bin/$1

