#!/usr/bin/env bash

# Try to run nix-shell wherever we find a shell.nix

function skip {
    grep -v "/Public/"      |
    grep -v "/nixpkgs/"     |
    grep -v "/git-html/"    |
    grep -v "/Haskell/ghc/" |
    grep -v "ML4HS/test-data/"
}

function all {
    locate -e shell.nix
    locate -e default.nix
}

ERR=0
PROCESSED=""
while read -r FILE
do
    DIR=$(dirname "$FILE")
    if echo "$PROCESSED" | grep "^${DIR}\$" > /dev/null
    then
        continue
    fi
    printf -v PROCESSED "%s\n%s" "$PROCESSED" "$DIR"
    (cd "$DIR"; nix-shell --show-trace --run true;) || ERR=1
done < <(all | skip)

exit "$ERR"
