#!/usr/bin/env bash

set -e

function bumpIn {
    (cd "$1"; bumpcommit)
}

bumpIn "/home/chris/Programming/Haskell/TreeFeatures"
bumpIn "/home/chris/Programming/Haskell/HS2AST"
bumpIn "/home/chris/Programming/Haskell/ML4HSHelper"
bumpIn "/home/chris/Programming/Haskell/ML4HS"
bumpIn "/home/chris/Programming/Haskell/MLSpec"
bumpIn "/home/chris/Programming/Haskell/ArbitraryHaskell"
bumpIn "/home/chris/Programming/Haskell/AstPlugin"
bumpIn "/home/chris/System/Packages/haskell-te"
bumpIn "/home/chris/warbo-utilities"
