#!/bin/sh

if git status | grep "modified:.*\.cabal" > /dev/null
then
    if [[ -e shell.nix ]]
    then
        echo "Old shell.nix:"
        cat shell.nix
        rm  shell.nix
    fi
    hsConfig
fi

cabal test
