#!/usr/bin/env bash
set -e

# -s prevents having to double-quote paths for SSH
# -r copies recursively
# --progress gives a progress bar
# --append-verify resumes from where it left off
# --inplace copies straight to the destination filename rather than a temp file
rsync -s -r --inplace --progress --append-verify "$@"
