#!/usr/bin/env bash
shopt -s nullglob

PASS=0
 ALL=0
 RUN=0

while read -r LINE
do
    NAME=$(basename "$LINE")
    ALL=$(( ALL + 1 ))
    [[ -e ~/.tests/results/pass/"$NAME"   ]] && PASS=$(( PASS + 1 ))
    [[ -e ~/.tests/results/stdout/"$NAME" ]] &&  RUN=$(( RUN + 1 ))
done < <(find ~/.tests/scripts -type f)

DIFF=$(( RUN - PASS ))

EXTRA=""
[[ "$ALL" -eq "$RUN" ]] || EXTRA=" so far"

if [[ "$DIFF" -gt 0 ]]
then
    echo "<fc=#FF0000>${PASS}/${RUN} passed${EXTRA}</fc>"
else
    echo "<fc=#00FF00>${PASS}/${RUN} passed${EXTRA}</fc>"
fi

[[ "x$1" = "xshow" ]] || exit 0

for TEST in ~/.tests/scripts/*
do
    NAME=$(basename "$TEST")
    [[ -e ~/.tests/results/stdout/"$NAME" ]] || continue
    [[ -e ~/.tests/results/pass/"$NAME"   ]] || echo "$NAME"
done
