#!/usr/bin/env bash
shopt -s nullglob

PASS=0
 ALL=0
 RUN=0

for LINE in ~/.tests/scripts/*
do
    NAME=$(basename "$LINE")
    ALL=$(( ALL + 1 ))
    [[ -e ~/.tests/results/pass/"$NAME"   ]] && PASS=$(( PASS + 1 ))
    [[ -e ~/.tests/results/stdout/"$NAME" ]] &&  RUN=$(( RUN  + 1 ))
done

DIFF=$(( RUN - PASS ))

EXTRA=""
[[ "$ALL" -eq "$RUN" ]] || EXTRA=" so far"

HEX="#00FF00"
[[ "$DIFF" -gt 0 ]] && HEX="#FF0000"

echo "<fc=${HEX}>${PASS}/${RUN} passed${EXTRA}</fc>"

[[ "x$1" = "xshow" ]] || exit 0

echo "PASS: $PASS"
echo "RUN: $RUN"
echo "ALL: $ALL"

echo "Passed:"
for TEST in ~/.tests/scripts/*
do
    NAME=$(basename "$TEST")
    [[ -e ~/.tests/results/pass/"$NAME" ]] && echo "$NAME"
done
echo ""

echo "Not run:"
for TEST in ~/.tests/scripts/*
do
    NAME=$(basename "$TEST")
    [[ -e ~/.tests/results/stdout/"$NAME" ]] || echo "$NAME"
done
echo ""

echo "Failures:"
for TEST in ~/.tests/scripts/*
do
    NAME=$(basename "$TEST")
    [[ -e ~/.tests/results/stdout/"$NAME" ]] || continue
    [[ -e ~/.tests/results/pass/"$NAME"   ]] || echo "$NAME"
done
