#!/usr/bin/env python

# More convenient grep
import sys
import subprocess
regex = '"' + sys.argv[1] + '"'
path  = (sys.argv + ['.'])[2]
cmd   = ' '.join(['grep -r',
                  regex,
                  path,
                  '| grep -v "\.svn" | grep -v "\.sql"'])
subprocess.call(cmd,
                shell=True,
                stderr=open('/dev/null', 'w'))
