#!/usr/bin/env bash
CMD="x2x -west -to :0"

if ssh jo@debian true 1> /dev/null 2> /dev/null
then
    echo "Found debian, starting x2x"
    ssh -Y jo@debian "$CMD"
else
    echo "Couldn't connect to debian, trying via raspberrypi"
    ssh -L20000:jo@debian:22 pi@raspberrypi
    ssh -p 20000 -X localhost "$CMD"
fi
