#!/usr/bin/env bash

if ssh jo@debian.local true
then
  echo "Killing synergy client for nixos" 1>&2
  ssh jo@debian.local "./killsyn nixos"

  echo "Killing synergy server" 1>&2
  killall -9 synergys

  ssh jo@debian.local "./synergy" &

  echo "Starting synergy server" 1>&2
  nix-shell -p synergy --run synergys
else
  echo "Can't connect to debian.local" 1>&2
  exit 1
fi
