#!/usr/bin/env bash

ssh jo@debian.local 'ps auxww | grep syn | grep bash | grep "\./synergy" | sed -e "s/ [ ]*/ /g" | cut -d " " -f 2 | while read -r P; do kill "$P"; done'
ssh jo@debian.local 'killall synergyc'
