#!/usr/bin/env bash

ssh -t jo@debian "pkill x11vnc; DISPLAY=:0 x11vnc" &

sleep 3

if OUTPUT=$(ping -c 1 debian)
then
  ADDR=$(echo "$OUTPUT" | grep -o "192\.168\.[0-9]*\.[0-9]*" | head -n1)
  echo "ADDRESS: $ADDR"
fi

