#!/bin/sh

# Tries to reduce 'Emacs pinky', caused by the position of Ctrl on PS/2
# keyboards

# Put Ctrl back to the correct place on the PS/2 layout. This is where Caps Lock
# is, so we map that to Ctrl. And nothing of value was lost.
HOST=$(hostname)

if [[ "x$HOST" = "xolpc" ]]
then
    setxkbmap -layout us # OLPC keyboard is US, but Ctrl is correctly placed
else
    if [ ! -d /nix ]  # NixOS does this with configuration.nix
    then
        setxkbmap -layout gb -option ctrl:nocaps # GB layout, CapsLock as Ctrl
    fi
fi

# Allow holding-down the space bar to act as Ctrl, so we can use our thumbs
s2cctl stop || true
killall s2c || true
s2cctl start
