#!/usr/bin/env python3
"""To make maintaining, backing up and syncing configuration files easier, we
keep them in a git repository and make symlinks in the relevant places.

This script makes the linking process easier. Run it from your home directory
give it the path to your dotfile directory with the '-df' option and optionally
the names of dotfiles you want to link.

The convention we follow is that everything in the dotfile directory, say
"my-dotfiles/foo", should be linked to a correspondingly named file in ~
prefixed with a ., say "~/.foo"."""

import sys
import os

# Check our arguments
if len(sys.argv) < 3 or '-df' not in sys.argv:
    print(__doc__)
    sys.exit()

dotfile_dir = sys.argv[sys.argv.index('-df') + 1]
files       = list(filter(lambda f: f != '-df' and f != dotfile_dir,
                          sys.argv[1:]))

# If we've not been given any files, use everything
if len(files) == 0:
    files = os.listdir(dotfile_dir)

# Prefix filenames to get full paths
dotfiles = map(lambda f: (dotfile_dir + '/' + f, '.' + f), files)

def link(src_dest):
    """Make a link to the given dotfile."""
    src, dest = src_dest
    if not os.path.exists(dest):
        os.symlink(src, dest)

for d in dotfiles:
    link(d)
