#!/usr/bin/env bash
NET=$(nmcli c | grep -v -- "--" | grep -v "DEVICE" | cut -d ' ' -f1)

if [[ "x$NET" = "xaa.net.uk" ]]
then
    echo "home"
    exit
fi

if [[ "x$NET" = "xUoD_WiFi" ]]
then
    echo "uni"
    exit
fi

if [[ "x$NET" = "xeduroam" ]]
then
    echo "uni"
    exit
fi

echo "unknown"
exit
