#!/usr/bin/env bash
NET=$(nmcli c | grep -v -- "--" | grep -v "DEVICE" | cut -d ' ' -f1)

ping -c 1 google.com 1>/dev/null 2>/dev/null || {
    echo "unknown"
    exit
}

if [[ "x$NET" = "xaa.net.uk" ]]
then
    echo "home"
    exit
fi

if [[ "x$NET" = "xUoD_WiFi" ]]
then
    echo "uni"
    exit
fi

if [[ "x$NET" = "xeduroam" ]]
then
    echo "uni"
    exit
fi

echo "unknown"
exit
