#!/bin/bash

# Backup MySQL's ramfs

# Only run if /var/lib/mysql_ram is non-empty
if [ $(whoami) = "root" ]; then
  if [ "$(ls -A /var/lib/mysql_ram)" ]; then
    DATE=$(date +"%Y-%m-%d-%H-%M")
    tar cjf /root/mysql_$DATE.tar.bz2 /var/lib/mysql_disk
    # TODO: Prune backups exponentially
    rm -rf /var/lib/mysql_disk/*
    cp -r /var/lib/mysql_ram/* /var/lib/mysql_disk/
  fi
else
  command -v gksudo >/dev/null 2>&1 && { gksudo true; }
  sudo -u root /usr/local/bin/mysql_backup $@
fi
