#!/bin/bash

# Backup MySQL's ramfs. See /var/lib/README.mysql for details.

# Only run if /var/lib/mysql_ram is non-empty
if [ "$(ls -A /var/lib/mysql_ram)" ]; then
  DATE=$(date +"%Y-%m-%d-%H-%M")
  tar cjf /home/chris.warburton/mysql_$DATE.tar.bz2 /var/lib/mysql_disk
  # TODO: Prune backups exponentially
  rm -rf /var/lib/mysql_disk/*
  cp -r /var/lib/mysql_ram/* /var/lib/mysql_disk/
fi
