#!/bin/bash
#
# Populate MySQL's ramfs from a backup. See /var/lib/README.mysql for details.
# mysqld starts at position 64, so we put ourselves in position 60.
#
# chkconfig: 2345 60 99

case "$1" in
  start)
    # Only run if /var/lib/mysql_ram is mounted
    if grep -q "[[:space:]]/var/lib/mysql_ram[[:space:]]" /proc/mounts; then
      cp -r /var/lib/mysql_disk/* /var/lib/mysql_ram/
      chown mysql.mysql /var/lib/mysql_ram -R
      echo "Populated /var/lib/mysql_ram"
      exit 0
    else
      echo "Error: /var/lib/mysql_ram is not mounted"
      exit 2
    fi
    ;;
  *)
    exit 0
esac
exit 0
