#!/usr/bin/env python
import sys
source = sys.stdin
args = sys.argv[1:]
while len(args) > 0:
    try:
        source = open(args.pop(0), 'r')
        break
    except:
        pass
for line in source:
    print line,