#!/usr/bin/env bash

# Run when plugging laptop back in, eg. after a meeting

# Set up multiple screens
bash ~/.screenlayout/uni.sh

# Set up keyboard
keys

# Set up wifi
read -s -p "UoD Wifi password: " password
WIFIID=$(nmcli -a c show       |
         grep UoD          |
         sed 's/[ ]* / /g' |
         cut -d ' ' -f 2)

nmcli c up "$WIFIID" passwd-file <(
    echo "802-1x.identity:cmwarburton"
    echo "802-1x.password:$password" )
