#!/bin/sh

# Run when plugging laptop back in, eg. after a meeting

# Set up multiple screens
bash ~/.screenlayout/uni.sh

# Set up keyboard
keys

# Set up wifi
WIFIID=$(nmcli -a c show | grep UoD | grep -o "[0-9a-f]*-[0-9a-f-]*" | grep -v 802-11 | grep -v "[-]-")
nmcli -a c up "$WIFIID"

