#!/usr/bin/env bash
set -e

# Open all useful PDFs

function isOpen {
    # shellcheck disable=SC2009
    ps auxww | grep mupdf-x11 | grep -q "$1"
}

function openIfNeeded {
    # Open $2 if it's not already (i.e. if `mupdf-x11 ... $1` appears in `ps`)
    if isOpen "$1"
    then
        echo "Already have reader for $2, skipping" 1>&2
    else
        echo "Opening $2" 1>&2
        mupdf-x11 "$2" &
    fi
}

while read -r LINE
do
    # Skip comments
    echo "$LINE" | grep -q '^\s*#' && continue
    UNIQUEID=$(echo "$LINE" | cut -f1)
    LOCATION=$(echo "$LINE" | cut -f2)
    openIfNeeded "$UNIQUEID" "$LOCATION"
done < ~/.pdfs
