#!/usr/bin/env bash

set -e
shopt -s nullglob

if [[ "$UID" -eq 0 ]]
then
    echo "Error: 'podcasts' won't work as root. Try running without sudo?" 1>&2
    exit 1
fi

# Mount the iPod, if it's plugged in
ipod || {
    echo "Failed to mount, exiting" 1>&2
    exit 1
}

[[ -d ~/iPod/Audio ]] || {
    echo "iPod doesn't seem to be mounted" 1>&2
    exit 1
}

echo "DELETING IPOD TO""DO" 1>&2

for D in ~/iPod/Audio/TO""DO/*
do
    echo "DELETING '$D'" 1>&2
    rm -rf "$D"
done

echo "MOVING NEW TO""DOS" 1>&2

for D in ~/Audio/TO""DO/*
do
    cp -rv "$D" ~/iPod/Audio/TO""DO/

    NAME=$(basename "$D")

    if [[ -d "$D" ]]
    then
        # Look for an existing directory with the same name, move the contents
        FOUND=0
        for DEST in ~/Audio/Non-fiction ~/Audio/Fiction
        do
            if [[ -d "$DEST/$NAME" ]]
            then
                for F in "$D"/*
                do
                    mv -v "$F" "$DEST/$NAME"/
                done
                rmdir "$D"
                FOUND=1
            fi
        done

        if [[ "$FOUND" -eq 0 ]]
        then
            echo "No existing '$NAME' found, assuming non-fiction" 1>&2
            mv -v "$D" ~/Audio/Non-fiction/
        fi
    else
        # Looking for existing files is too tedious; assume it's standalone
        echo "Standalone file '$D' found, assuming non-fiction" 1>&2
        mv -v "$D" ~/Audio/Non-fiction/
    fi
done
