#!/usr/bin/env python

import sys
from subprocess import call

known = {}
with open(sys.argv[sys.argv.index('-f') + 1], 'r') as f:
    for line in f.readlines():
        this = line.split('  ', 1)
        known[this[1].strip()] = this[0].strip()

for line in sys.stdin.readlines():
    if line.strip() not in known:
        call(['md5sum', line.strip()])
        sys.stdout.flush()
