#!/usr/bin/env bash

# allow settings to be updated via environment
: "${xvfb_lockdir:=/tmp/xvfb-locks}"
: "${xvfb_display_min:=99}"
: "${xvfb_display_max:=599}"

mkdir -p -- "$xvfb_lockdir" || exit

i="$xvfb_display_min"     # minimum display number
while (( i < xvfb_display_max )); do
  if [ -f "/tmp/.X$i-lock" ]; then                # still avoid an obvious open display
    (( ++i )); continue
  fi
  exec 5>"$xvfb_lockdir/$i" || continue           # open a lockfile
  if flock -x -n 5; then                          # try to lock it
    exec xvfb-run --server-num="$i" "$@" || exit  # if locked, run xvfb-run
  fi
  (( i++ ))
done
