#!/bin/bash

# Mount a zram filesystem for MySQL/MariaDB
if [ $(whoami) = "root" ]; then
  if grep -q "[[:space:]]/var/lib/mysql_ram[[:space:]]" /proc/mounts; then
    # Already mounted
    echo "Already mounted"
  else
    # Enable one zram device
    modprobe -r zram
    modprobe zram num_devices=1
    # Make it 1.5GiB (uncompressed size)
    echo $(((1024 + 512) * 1024 * 1024)) > /sys/block/zram0/disksize
    # Give it a filesystem
    mke2fs /dev/zram0
    # Mount it for use by MySQL/MariaDB
    mount /dev/zram0 /var/lib/mysql_ram
  fi
else
  # We need to be root; sudo then recurse
  command -v gksudo >/dev/null 2>&1 && { gksudo true; }
  sudo -u root /usr/local/bin/zram_mount $@
fi
