#!/bin/bash

# Turns on XDebug for PHP
if [ $(whoami) = "root" ]; then
  echo "zend_extension=/usr/lib/php5/20100525/xdebug.so
xdebug.remote_enable=1
xdebug.var_display_max_depth=12
xdebug.var_display_max_data=10000
" > /etc/php5/mods-available/xdebug.ini
  service apache2 restart

else
  gksudo true
  sudo xdebugon $@
fi
