#!/usr/bin/env bash

# Start agenda from half an hour ago
NOW=$(date "+%s")
DELTA=$((60 * 30))
THEN=$((NOW - DELTA))
DATE=$(date -d "@$THEN" "+%Y-%m-%dT%H:%M")

CMD="gcalcli --military --nocolor agenda '$DATE'"

if command -v gcalcli > /dev/null
then
    RESULT=$($CMD)
    CODE=$?
else
    RESULT=$(nix-shell -p gcalcli --run "$CMD")
    CODE=$?
fi

if [[ "x$1" = "xhead" ]]
then
    echo "$RESULT" | grep '[0-9]' | head -n1 | sed -e 's/  */ /g'
else
    echo "$RESULT"
fi

exit "$CODE"
