#!/usr/bin/env bash

GMAIL=$(ls ~/Mail/gmail/INBOX/new | wc -l)
DUNDEE=$(ls ~/Mail/dundee/INBOX/new | wc -l)

if [[ "$GMAIL" -eq 0 ]]
then
    GMAILCOL="gmail $GMAIL"
else
    GMAILCOL="gmail <fc=#44ff66>$GMAIL</fc>"
fi

if [[ "$DUNDEE" -eq 0 ]]
then
    DUNDEECOL="dundee $DUNDEE"
else
    DUNDEECOL="dundee <fc=#44ff66>$DUNDEE</fc>"
fi

echo "$GMAILCOL | $DUNDEECOL"
