#!/usr/bin/env bash

# get_iplayer wraps its output depending on COLUMNS. We set a big value to try
# and minimise the impact this has on our parsing.
export COLUMNS=5000

NAME=$(basename "${@: -1}")

{
    echo "Saving to '$NAME' in:"
    for X in 5 4 3 2 1
    do
        echo "$X"
        sleep 1
    done
} 1>&2

# Make get_iplayer to show progress https://stackoverflow.com/a/32981392/884682
function faketty () {
    script -qfc "$(printf "%q " "$@")";
}

# Display and store stdout https://stackoverflow.com/a/12451419/884682
exec 5>&1
OUTPUT=$(faketty get_iplayer --no-purge --modes=good --raw "$@" |
         tee >(cat - >&5))

SOURCE=$(echo "$OUTPUT" | tail -n1 | grep -o '/[^:]*$')

if [[ -f "$SOURCE" ]]
then
    mv -v "$SOURCE" "$NAME"
fi
