#!/usr/bin/env bash

# FIXME: Move to scripts/ and run jsbeautifier

URL="$1"
[[ -n "$URL" ]] || {
    echo "No URL given, reading from stdin" 1>&2
    URL=$(cat)
}

wget -q -O- "$URL" | grep -o 'http[^ "]*mp4'
