#!/usr/bin/env bash

EXTRA=""
if echo "$*" | grep -q yout
then
    echo "Looking up available formats" 1>&2

    # youtube-dl puts progress/debug info on stdout instead of stderr. We
    # try filtering this out by only keeping lines beginning with a digit.
    FORMATS=$(youtube-dl -F "$@" | grep '^[0-9]')

    echo "Formats are:" 1>&2
    echo "$FORMATS"     1>&2

    if [[ "$#" -eq 1 ]]
    then
        echo "Only 1 arg given, which seems to be a youtube URL"            1>&2
        echo "Assuming we want format 43 (WebM), falling back to 18 (AVC1)" 1>&2
        EXTRA="-f 43/18/93/medium"
    fi
fi

if echo "$*" | grep -q ted.com
then
    echo "Trying medium format TED talk; falling back to any format" 1>&2
    youtube-dl --fixup never -f medium "$@" ||
    youtube-dl --fixup never           "$@"
else
    # shellcheck disable=SC2086
    youtube-dl --fixup never $EXTRA "$@"
fi
